import { MigrationInterface, QueryRunner } from "typeorm"

export class insertDataToProduct1675523482242 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Potato', 'https://i5.walmartimages.ca/images/Enlarge/094/561/6000200094561.jpg', (SELECT id FROM product_tag WHERE name='vegetables'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Tomato', 'https://i5.walmartimages.ca/images/Enlarge/008/475/6000190008475.jpg', (SELECT id FROM product_tag WHERE name='vegetables'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Onions', 'https://i5.walmartimages.com/asr/a17b4251-be9b-4ae3-8d71-1f427930c520.2921cb7c559c4b55d91de9567cbff634.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF', (SELECT id FROM product_tag WHERE name='vegetables'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Bell peppers', 'https://i5.walmartimages.com/asr/7be94a8e-9a5d-4f87-842f-5fe4084138ba.c95d36e140f5e0d492ca632b42e4543c.jpeg', (SELECT id FROM product_tag WHERE name='vegetables'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Cucumber', 'https://i5.walmartimages.com/asr/5985ccc8-109e-411d-aca7-556ab217e1da.e3770028b0d00b3fa4e6a40c4e630ef9.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', (SELECT id FROM product_tag WHERE name='vegetables'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Salad', 'https://img.freepik.com/premium-photo/fresh-green-lettuce-salad-leaves-isolated-white-background-clipping-path-full-depth-field_228338-518.jpg?w=740', (SELECT id FROM product_tag WHERE name='herbs'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Spinach', 'https://lettuceinfo.org/wp-content/uploads/2020/09/Spinach.jpg', (SELECT id FROM product_tag WHERE name='herbs'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Champignons', 'https://static.zhiva.ua/cache/products/97/catalog_product_main_2318.jpg', (SELECT id FROM product_tag WHERE name='mushrooms'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Banana', 'https://i5.walmartimages.com/asr/3bbb1151-d69a-43fb-b132-47e0bc066307.1f28c1acf3df725a6a39ba4c8738e025.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', (SELECT id FROM product_tag WHERE name='fruits'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Strawberry', 'https://i5.walmartimages.com/asr/25733901-b0cd-4f45-8e2d-70416e6710be_1.49c9e5d6df766cc37ef991c3258a4e71.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', (SELECT id FROM product_tag WHERE name='fruits'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Grape', 'https://i5.walmartimages.com/asr/7c2c73db-7793-4c94-9de5-70b47d1abd65.97ebb3191bf028e16e7e6c3ea31a6497.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', (SELECT id FROM product_tag WHERE name='fruits'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Apple', 'https://i5.walmartimages.com/asr/f46d4fa7-6108-4450-a610-cc95a1ca28c5_3.38c2c5b2f003a0aafa618f3b4dc3cbbd.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', (SELECT id FROM product_tag WHERE name='fruits'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Watermelon', 'https://i5.walmartimages.com/asr/7eaaef1a-e70d-4ad1-983a-0d32f3207aba_1.25f407d7eea58042f2e714def085de92.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', (SELECT id FROM product_tag WHERE name='fruits'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Orange', 'https://i5.walmartimages.com/asr/e3047114-663b-4d6f-99e3-f39a1783cc85_1.dd4e87c150c5f739fc07655139fcbf66.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', (SELECT id FROM product_tag WHERE name='fruits'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Lemon', 'https://i5.walmartimages.com/asr/f025c57c-13e1-4a1a-ac81-0695aaf2473d.7f3c9f067735c2730223c9147a646f7c.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', (SELECT id FROM product_tag WHERE name='fruits'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Brown bread', 'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2950306.jpg', (SELECT id FROM product_tag WHERE name='cereals'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('White bread', 'https://thumbs.dreamstime.com/b/fresh-sliced-bread-white-background-4798485.jpg', (SELECT id FROM product_tag WHERE name='cereals'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Blueberry', 'https://i5.walmartimages.com/asr/34ba2007-7e7a-4c2f-929c-0af5dcbecee8_1.ac9c9a9b73d769183cebe981d6c320be.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', (SELECT id FROM product_tag WHERE name='berries'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Walnut', 'https://previews.123rf.com/images/utima/utima1712/utima171200041/91703186-walnut-isolated-walnuts-isolated-on-white-background-with-clipping-path-.jpg', (SELECT id FROM product_tag WHERE name='nuts'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Apple juice', 'https://thumbs.dreamstime.com/b/white-background-apple-juice-glass-next-to-139744867.jpg', (SELECT id FROM product_tag WHERE name='juices'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Flour', 'https://thumbs.dreamstime.com/b/wheat-flour-isolated-white-background-deep-focus-138962962.jpg', (SELECT id FROM product_tag WHERE name='cereals'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Catfish', 'https://thumbs.dreamstime.com/b/catfish-white-clipping-path-isolated-background-inside-35649592.jpg', (SELECT id FROM product_tag WHERE name='fish'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Pike', 'https://thumbs.dreamstime.com/b/fishing-big-live-pike-fish-isolated-white-background-perspective-view-120005316.jpg', (SELECT id FROM product_tag WHERE name='fish'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Сhicken egg', 'https://media.istockphoto.com/id/916185054/photo/group-of-three-white-eggs-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=y8Ju4ZXyJqHMNfm30qpPMh_ik8i1B_4Enih91pDuia8=', (SELECT id FROM product_tag WHERE name='eggs'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Milk', 'https://img.freepik.com/premium-photo/glass-milk-white-background_269353-747.jpg?w=2000', (SELECT id FROM product_tag WHERE name='dairy'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Yogurt', 'https://previews.123rf.com/images/baibaz/baibaz1611/baibaz161100005/65177175-bowl-of-greek-yogurt-isolated-on-white-background.jpg', (SELECT id FROM product_tag WHERE name='dairy'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Ice cream', 'https://previews.123rf.com/images/ifong/ifong1011/ifong101100010/8111185-scoop-of-vanilla-ice-cream-isolated-on-white-background.jpg', (SELECT id FROM product_tag WHERE name='dairy'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Butter', 'https://previews.123rf.com/images/dianazh/dianazh1207/dianazh120700727/14446362-piece-of-butter-on-white-background.jpg', (SELECT id FROM product_tag WHERE name='dairy'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Sugar', 'https://thumbs.dreamstime.com/b/granulated-white-sugar-wooden-bowl-isolated-background-clipping-path-179187427.jpg', (SELECT id FROM product_tag WHERE name='spices'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Olive oil', 'https://previews.123rf.com/images/dusanzidar/dusanzidar1502/dusanzidar150200028/36957076-olive-oil-and-olive-branch-on-white-background.jpg', (SELECT id FROM product_tag WHERE name='oil'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Chicken', 'https://thumbs.dreamstime.com/b/fresh-raw-whole-chicken-white-background-fresh-raw-chicken-white-background-125776416.jpg', (SELECT id FROM product_tag WHERE name='meat'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Garlic', 'https://i5.walmartimages.com/asr/f3888ba0-1a79-4197-8330-8fc6378f898e.7ca63a6404e9194de043c04618331f98.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', (SELECT id FROM product_tag WHERE name='vegetables'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Rice', 'https://thumbs.dreamstime.com/b/bowl-tasty-cooked-rice-white-background-149957455.jpg', (SELECT id FROM product_tag WHERE name='porridge'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Dark chocolate', 'https://img.freepik.com/premium-photo/dark-chocolate-bar-isolated-white-background_33736-3638.jpg?w=2000',(SELECT id FROM product_tag WHERE name='chocolate'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Milk chocolate', 'https://s3.amazonaws.com/stockfreedom/wp-content/uploads/2018/03/11190719/sf01105481sm.jpg', (SELECT id FROM product_tag WHERE name='chocolate'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('White chocolate', 'https://thumbs.dreamstime.com/b/white-chocolate-pieces-isolated-white-background-delicious-dessert-white-chocolate-pieces-isolated-white-background-166593859.jpg', (SELECT id FROM product_tag WHERE name='chocolate'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Mozzarella', 'https://thumbs.dreamstime.com/b/buffalo-mozzarella-white-background-176820648.jpg', (SELECT id FROM product_tag WHERE name='dairy'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Sunflower oil', 'https://previews.123rf.com/images/yasonya/yasonya1108/yasonya110800048/10352569-sunflower-oil-with-flower-isolated-on-white-background.jpg', (SELECT id FROM product_tag WHERE name='oil'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Powder', 'https://t4.ftcdn.net/jpg/01/78/89/21/360_F_178892188_nfW6fL2o1L0dMt1ZRlmAbdd0zMltKity.jpg', (SELECT id FROM product_tag WHERE name='spices'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Salt', 'https://img.freepik.com/premium-photo/salt-white-bowl-isolated-white-background-top-view_253984-5100.jpg?w=2000', (SELECT id FROM product_tag WHERE name='spices'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Honey', 'https://img.freepik.com/premium-photo/glass-jar-pure-honey-with-honey-dipper-isolated-white-background_252965-49.jpg?w=2000', (SELECT id FROM product_tag WHERE name='spices'))`)
        await queryRunner.query(`INSERT INTO product(name, "imgUrl", "productTagId") VALUES('Pasta', 'https://previews.123rf.com/images/tobi/tobi0906/tobi090600043/5030637-boiled-spaghetti-on-white-background.jpg', (SELECT id FROM product_tag WHERE name='porridge'))`)


    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DELETE FROM product`)
    }

}
